AUTHENTIK_EMAIL__HOST: localhost
AUTHENTIK_EMAIL__PORT: 25

AUTHENTIK_EMAIL__USERNAME: ""
AUTHENTIK_EMAIL__PASSWORD: ""

AUTHENTIK_EMAIL__USE_TLS: false
AUTHENTIK_EMAIL__USE_SSL: false

AUTHENTIK_EMAIL__TIMEOUT: 10
AUTHENTIK_EMAIL__FROM: authentik@localhost

AUTHENTIK_COMPOSE_PORT_HTTP: 80
AUTHENTIK_COMPOSE_PORT_HTTPS: 443

authentik_project_dir: /opt/authentik
