- name: Load Debian-specific variables
  include_vars:
    file: "defaults/debian.yml"

- name: Merge system_packages and additional_system_packages
  set_fact:
    system_packages: "{{ system_packages + additional_system_packages | default([]) }}"

- name: Print merged system_packages
  debug:
    var: system_packages

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install System packages
  ansible.builtin.package:
    name: "{{ system_packages }}"
  become: true
