- name: Essentials Playbook! Setup systems with basic tooling.
  hosts: all
  roles:
    - name: system/repository
      become: true

    - name: system/package
      become: true

    - name: system/cargo
      become: true

    - name: system/pipx
      become: false
