- name: Ensure required packages are installed (Debian-based systems)
  apt:
    name:
      - build-essential
      - git
      - pkg-config
      - libssl-dev
      - libmariadb-dev-compat
      - libmariadb-dev
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure required packages are installed (RHEL-based systems)
  yum:
    name:
      - gcc
      - git
      - pkgconfig
      - openssl-devel
      - mariadb-connector-c-devel
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'
  
- name: Ensure the project directory exists
  file:
    path: ./vaultwarden  # Replace with the desired directory
    state: directory

- name: Clone the Vaultwarden repository if not already present
  git:
    repo: https://github.com/dani-garcia/vaultwarden
    dest: ./vaultwarden
    update: no

- name: Pull the latest changes if the repo already exists
  git:
    repo: https://github.com/dani-garcia/vaultwarden
    dest: ./vaultwarden
    update: yes
  when: "'vaultwarden' in ansible_facts.filesystem_items['./vaultwarden']"

- name: Build the Vaultwarden project
  shell: |
    cargo build --features mysql --release
  args:
    chdir: ./vaultwarden
  environment:
    CARGO_HOME: "{{ ansible_env.HOME }}/.cargo"
