- name: Create a system user for the Vaultwarden service
  ansible.builtin.user:
    name: vaultwarden
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Install the vault
  ansible.builtin.copy:
    src: {{ vault_binary }}
    dest: /usr/local/bin/vault
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: '0644'

- name: Install the webvault
  ansible.builtin.copy:
    src: {{ webvault_binary }}
    dest: /usr/local/bin/webvault
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: '0644'

- name: Install systemd Service for Vaultwarden
  ansible.builtin.template:
    src: templates/my-service.service.j2
    dest: /etc/systemd/system/vaultwarden.service
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: '0644'
        
- name: Reload systemd to apply the new service file
  ansible.builtin.command:
    cmd: systemctl daemon-reload

- name: Enable and start the service
  ansible.builtin.service:
    name: vaultwarden
    enabled: yes
    state: started
