- name: Build or install Vaultwarden
  include_tasks: build.yml
  when: vaultwarden_build | default(false)

- name: Install Vaultwarden from binary
  include_tasks: binary.yml
  when: not vaultwarden_build | default(false)

# get binary by building or by downloading it
# then install it