- name: Check if SSH private key exists
  stat:
    path: "{{ ansible_ssh_private_key_file }}"
  register: ssh_key_check

- name: Generate SSH key if it does not exist
  delegate_to: localhost
  run_once: true
  openssh_keypair:
    path: "{{ ansible_ssh_private_key_file }}"
    type: ed25519
    state: present
    mode: '0600'
  when: not ssh_key_check.stat.exists
  register: ssh_keygen_result
